name: Build Prowler Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'prowler/**'
  pull_request:
    branches:
      - main
    paths:
      - 'prowler/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image for Prowler
        run: |
            cd prowler
            IMAGE_NAME='gorje6/ecs-prowler'
            TAG="${{ github.sha }}"
            docker build -t $IMAGE_NAME:latest .
            docker push $IMAGE_NAME:latest
